### ISSUE TITLE
Layout Shift when using preview prop

### ISSUE THREAD

**Issue by georgeosutton** [coreyward/sanity-image#22] opened 2023-04-04 16:08 UTC
Noticed that when I pass in a preview image as outlined in examples I'm getting layout shift when the image is loading. Can cause images below the fold to overflow the page.

**Comment by coreyward** [comment] 2023-04-04 18:01
Can you provide a reproduction in CodeSandbox or similar? At the very least, more detail would be helpful. 

I suspect the issue is that you aren’t styling the image to account for cases where it is smaller than the desired display size, and then when the full-size image loads, you wind up with the element changing size, but it's hard to say for sure without knowing more.

**Comment by georgeosutton** [comment] 2023-04-04 22:39
Cool yeah defining a width on containing element fixed the issue.

**Comment by georgeosutton** [comment] 2023-04-05 11:43
I'm getting layout shift on a simple example like this though.

```
<div className={styles.container}>
     <SanityImage
        className={styles.image}
        id={image.asset._id}
        baseUrl="https://cdn.sanity.io/images/12345/production/"
        alt={image?.alt || ""}
        preview={image.asset.metadata.lqip}
        hotspot={image.hotspot}
        crop={image.crop}
        />
 </div>
```
```
.container {
  width: 50%;
}
.image {
  max-width: 100%;
  width: 100%;
  height: auto;
}
```

**Comment by georgeosutton** [comment] 2023-04-05 12:55
#23 Feel like this could be the root cause of the issue.

**Comment by coreyward** [comment] 2023-04-05 18:51
@georgeosutton Okay, I’m going to close this in favor of that issue, but if after that gets resolved you still have issues we can re-open this and explore further.

**Closed as completed by coreyward** 2023-04-05 18:51 UTC
