### ISSUE TITLE
When using preview, main image won't ever show unless it overlaps the visible area (usually the preview image)

### ISSUE THREAD

**Issue by fvieira** [coreyward/sanity-image#40] opened 2023-09-01 18:54 UTC
Hi @coreyward, first of all thanks a lot for this awesome library that finally allowed us to start using hotspot/crop easily!

I've stumbled upon an issue which feels like it's a problem in the library, but maybe I'm using it wrong.

When we use a preview, we get two img tags, but unless we use the right styles (e.g. using `display: flex`) in the wrapper div, the second img tag (the main image) is rendered besides or below the preview img, like this:
![2023-09-01_19-48](https://github.com/coreyward/sanity-image/assets/390867/e362e7ae-98f8-4cd1-9afd-e6967cea3d1d)

This in turn means it may get rendered in a place that is not visible and the browser never initiates the loading of the image, meaning the preview never gets replaced.

There's a bunch of ways to fix this with CSS from outside the library, but it would be nice if we could avoid this altogether directly in the library, though I'm not sure how without introducing a wrapper div around the two images (so we can ensure they stay on top of each other), and having a wrapper div probably goes against the idea of this library being just an img tag.

For now I introduced this hack which seems to work everywhere I need it too, but it's definitely not library-quality code:
```
.image[data-loading='true'] {
  // HACK: Usually ensures that independently of the position of the
  // main image during loading compared to the preview image
  // (usually it's on top, to the right, or to the left),
  // the main image overlaps with the preview image and thus is considered visible.
  transform: translate(-10%, -10%);
}
```

**Comment by coreyward** [comment] 2023-10-19 15:25
Hi @fvieira! This is expected behavior. The browser needs to have the primary image shown in the viewport in order to trigger the loading behavior. This is documented in the README as well (shown below for convenience). The default styles used to achieve this work in most cases, but as you have found, there are cases where clipping or other styles require you to make adjustments.

<img width="868" alt="Screenshot 2023-10-19 at 10 21 49 AM" src="https://github.com/coreyward/sanity-image/assets/81224/9e9168df-c1fa-485e-bb3d-52407d4e55df">

As you mention, there aren't any great workarounds on this. At best the dev experience could be improved, but I haven't come up with anything on that front. Since it looks like you've addressed this for your app I'm going to close this, but if you have additional thoughts I'm happy to continue the conversation.

**Closed as completed by coreyward** 2023-10-19 15:25 UTC

**Comment by fvieira** [comment] 2023-10-19 15:45
Hi @coreyward, thanks for your reply! I hadn't noticed that "Minor gotcha" section... Maybe it shouldn't be hidden, or at least I wouldn't call it a "Minor" gotcha as it has quite the sneaky impact, it's easy to use the component in lots of places successfully, build trust in it, and suddenly use it in a new place and have images not showing up for no apparent reason.

Also, not sure what's the "spaceball image" mentioned in the text... :sweat_smile: 

But yeah, other than making the warning more clear, I also have no perfect workaround that doesn't imply adding a wrapper div... For now I've replaced my workaround above (which isn't great as it makes the image show up with a drift animation if there is a `transition: transform`) with the one below which can be made to work easily by adding a `position: relative` to the wrapper div, but it even seems to work in other cases for some reason.

```
.image[data-loading='true'] {
  position: absolute;
  top: 0;
  left: 0;
}
```

But anyway, thanks for your work on this library, it is a lifesaver! :grin:
